<?php

namespace CharlesBundle\Repository;

/**
 * NounouRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NounouRepository extends \Doctrine\ORM\EntityRepository
{
}
