<?php

namespace CharlesBundle\Repository;

/**
 * SurveillanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveillanceRepository extends \Doctrine\ORM\EntityRepository
{
}
